name: App Client CI
on:
  push:
    branches: [main, preprod, staging, develop]
    paths: ["app-client/**"]
  pull_request:
    branches: [main, preprod, staging, develop]
    paths: ["app-client/**"]
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app-client
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: npm
          cache-dependency-path: app-client/package-lock.json
      - run: npm ci
      - run: npm run build
